SELECT
	RSB.SHPINV
	,RSB.SHPDTE
	,RSB.CABBV
	,RSB.CPART
	,RSB.F3WRBG
	,RTB.PDATE
	,RTB.PTIME
	,RTB.PUSER
FROM 
	FUTDTALIB.RSPSHPB AS RSB
LEFT JOIN
	FUTDTALIB.RSPSHSTA AS RTB
ON 
	RSB.SHPINV = RTB.SHPINV
ORDER BY RSB.SHPDTE DESC